{{# written 29 july, 2026 #}}
typewriter: {
    charDelay: 80
    newlineDelay: 500
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 600
        ".": 1200
        "?": 1200
    }
}
What [speed 60]was it al[speed 80]l for again?[sleep 150][newline]
The [jitter "secrecy" 5 shared],[newline]
the [jitter "intelligence" 5 shared],[newline]
the [jitter "counter-intelligence" 8 shared],[newline]
the [jitter "exhausting " 10 shared][sleep 100][jitter "propaganda" 10 shared][jitter "?" 10][newline]
Wha[speed 60]t was it [speed 80]all [speed 60]for?[speed 80][sleep 750][newline]
[speed 60]Just some [speed 80][sleep 145][jitter "fucking" 10][sleep 90] [speed 60]guy?[speed 80][sleep 1000][newline]
[speed 55]Well[speed 80],[sleep 650] [speed 40]thou[speed 65]sands of [speed 80]guys.[sleep 1390][newline]
[speed 65]/It was for them./[sleep 480][linebreak]

[sleep 700][function "end"]