{{# written 11 sept, 2026 #}}
typewriter: {
    charDelay: 45
    newlineDelay: 700
    textColor: #ffffff
    backgroundColor: #000000
    wordWrap: 120
    customDelays: {
        ",": 680
        ".": 700
        "?": 600
        "–": 980
    }
}
I really hate the city. All the noise, all the cars, all the people[sleep 450]–oh, I /hate/ people.[sleep 250] I ask my parents if I can go to grandpa and grandma’s house every chance I get, as it’s quite rural. Very rural, actually. It’s as close to the “boonies” as you can get, on Mars anyway, save for Western New Scotland. Oh–[sleep 200]Would Argyre City count as the boonies? Maybe, too many rich people over there. It’s far, too. Waaaay far from here. Anyway.[linebreak]

They let me go. Usually.[sleep 250][linebreak]

When they do let me go, oh my /god/, it’s /heaven/.[sleep 458] No noise, no traffic, no people, no nothin’. Just grass. And fields. The occasional tree–during terraforming they didn’t really plant trees out here, and they haven’t had time to spread here from the areas they /did/ plant them–the area where my grandparent’s house is doesn’t have all that many trees. You can see for a long while. And all you see is grass, maybe one tree. It’s great.[linebreak]

The [function "sine" 3 0.6 0.5][gradient "sky" "90deg, #c8d8fb, #9f9ff5"] is nice and clear, too. No light pollution, another plus. Even in the day, the sky is unusually clear. It’s awesome.[linebreak]

And you can see the ships. That’s probably my favorite part.[linebreak]

There are always ships flying overhead. Always. Not nearly as much as the cities–there are so many ships in the cities you can hear them
[custom "." 1400].[sleep 2500] I was exaggerating. You can’t hear them, but it sure as hell feels like you can–But it’s probably one or two ships per hour.[sleep 2500] Not really. I lied again.[custom "." 700][linebreak]

But I spend enough time outside that I’ve gotten to know the traffic pretty well. The commercial ships are easy. They run on schedules, and after enough weekends at Grandma and Grandpa’s, you start to recognize them. Same routes, same times, over and over again. I know which ones I should see on a Monday morning and which ones pass overhead in the afternoon.[linebreak]

Personal ships are different. There are way too many of them, and they come and go whenever they feel like it. I could never keep track of those. Every now and then there’s a military ship, too, but those are rare enough that I usually remember seeing them.[linebreak]

Commercial ships, though? Those are predictable. Very predictable. And in all my time watching them, I’d never seen a new one.[linebreak]

Wednesdays are my favorite. I never miss it. It’s when the /Lawrence of Arabia/ passes over. I know its the /Lawrence of Arabia/ because the lettering is so huge I can read it–I think two or three of me, standing on each other's shoulders, could fit in the hole of the O.[linebreak]

I can feel like I can feel it, its engines–hear it, too. It’s almost touching the atmosphere. It’s a huge Garden\-class superfreighter. A little over a kilometer long. It’s absolutely insane. I’ve been told that 300 years ago we barely had a space program–that’s what I was told, anyway. Now we have /that/. A ship the size of a small town. Flying over a small town. Regularly. As if it’s nothing. If that’s what we achieved in 300 years, what will we achieve in 300 years from now? I can’t even imagine.[linebreak]

[$start][custom "," 550][custom "." 900]Yesterday, though, there was a new ship. /Ancerene Wisse,/ I think it said on the side. Pretty sure it was a Venus\-class. It came down and landed a ways far from here. There's wasn't even a port or anything. No infrastructure. I thought it was weird. Usually when a ship lands, it lands for a reason. You /see/ the reason. It was far away, but I could /see/ it. I don’t know what it was doing though, I couldn’t tell. My binoculars were broken. People might’ve been coming out of it? But why? There was nothing around. Not even roads. None to, none from. Not even one of those automated cargo crawlers. Even after dinner, as the sky dimmed, it was still there. I asked grandpa about it, while he was having his even coffee–who does that? Have evening coffee, I mean. Isn’t it supposed to wake you up?[linebreak]

“What ship?” He said. I pointed to it.[linebreak]

He told me to leave it alone. So I did.[linebreak]

Next morning, it was gone.

[linebreak instant][sleep 1700][function "end"]
