{{# written 18 july, 2026 #}}
typewriter: {
    charDelay: 50
    newlineDelay: 100
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 350
        ".": 700
    }
    wordWrap: 80
}
[sleep 1000]
In 2129, researchers discovered a relatively inexpensive method of mass\-producing oganesson. Previously extraordinarily rare, this discovery drastically reduced the cost of synthesis. Oganesson proved to be a remarkably effective fuel source, exhibiting both conventional and anomalous properties. This breakthrough dramatically reduced the cost of spaceflight, making large\-scale expansion beyond Earth economically viable. With this discovery, a permanent space age began in 2139.[linebreak]

Over the next two decades, advances in propulsion and orbital industry allowed humanity to further colonize Earth's orbit, and extend into the orbit of the Moon. By 2150, there were hundreds of civilian habitats in orbit around Earth and the Moon, and, over the years that followed, the surface of the Moon was populated.[linebreak]

Additionally, the anomalous properties of oganesson allowed space\-faring vessels to be mass\-produced on scales that were thought only possible in science fiction.[linebreak]

On March 18th,[sleep 100] 2168,[sleep 100] oganessologists stationed in the Aitken Basin Research Complex discovered that, when combined with technetium, oganesson would continuously compound any acceleration applied to it.[sleep 800][linebreak]

[speed 70]And so, the outer reaches of the solar system were connected.[sleep 800][linebreak]

[speed 50]
By 2174, humanity had set their sights to terraform Mars,[sleep 200] and,[sleep 100] on May 23rd,[sleep 100] 2261,[sleep 100] at 18:[sleep 200]50:[sleep 200]47[sleep 200] Standard Sol Time, it was declared complete.[sleep 1500][linebreak]

Thus,[sleep 650] humanity turned elsewhere.[sleep 1000][linebreak]

[sleep 700][function "end"]