{{# written 18 july, 2026 #}}
typewriter: {
    charDelay: 50
    newlineDelay: 100
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 350
        ".": 700
        "–": 700
    }
    wordWrap: 80
}
[sleep 800]
In 2089, researchers discovered a relatively inexpensive method of mass\-producing oganesson. Previously extraordinarily rare, this discovery drastically reduced the cost of synthesis. Oganesson proved to be a remarkably effective fuel source for its price, exhibiting both conventional and, in the future, anomalous properties. This breakthrough dramatically reduced the cost of launching and operating spacecraft, making large\-scale expansion beyond Earth economically viable. By 2093, humanity had entered what would become known as the Permanent Space Age.[linebreak]

Just two years later, in 2095, the colonization of Luna began. What initially began as a small collection of research and industrial settlements soon developed into a vast center of education and technological development, housing hundreds of thousands of scientists, engineers, and educators. Over the following decades, Luna’s population would continue to expand until it became the most populous moon in the Solar System.[linebreak]

Between 2095 and 2125, advances in propulsion and orbital industry allowed humanity to expand throughout the space surrounding Earth and Luna. Orbital habitats, shipyards, research stations, and industrial facilities became increasingly common, with much of the infrastructure necessary for a permanent presence in space being established during this period. By 2125, humanity had developed an extensive network of settlements and infrastructure throughout cislunar space, with Luna serving as its primary center of population and industry.[linebreak]

The anomalous properties of oganesson continued to attract scientific interest, though they had little practical application at first. On its own, oganesson was an inexpensive, but rather poor, propellant. Its extraordinarily low cost, however, more than made up for its inefficiency. Compared to previous propulsion methods, oganesson was cheap enough to make large\-scale spaceflight economically viable, and it soon become the most widely used propellant in the world, and eventually, the Solar System.[linebreak]

One of its anomalous properties was discovered early in its study. When compressed to a sufficiently high density and subjected to an electrical charge, it would continuously dampen inertia and acceleration within a spherical field surrounding it. This allowed the construction of spacecraft on a scale far larger than anything previously thought possible.[linebreak]

On March 18th, 2126, another one of its anomalous properties was discovered. Oganessologists stationed in the Aitken Basin Research Complex–which would later become known as the Aitken University Center for Oganessonologics–found that, when combined with technetium, it would continuously compound any acceleration applied to it.[linebreak]

And so, humanity conquered the Solar System.[linebreak]

Within the next five years, every planet in the Solar System was visited. A year later, Mercury became a penal planet, the final destination of Earth’s criminals. Two years later, airships began flying in the Venutian atmosphere. Another two years later, the asteroid belt became a permanent industrial hub, harvesting billions of kilograms of raw materials and further accelerating humanity’s expansion.linebreak]

And, In 2138, humanity began their magnum opus: terraforming Mars.[linebreak]

What followed was a project of immense scale and extraordinary difficulty. Generation after generation worked to reshape the planet, with progress measured not in years, but in decades. Vast quantities of materials moved, atmosphere altered, temperatures raised, lives lost. Entire industries were built around the effort, and countless lives were devoted to a project whos completion none of its original architects would live in flesh to ever see.
After nearly a century and a half, on May 23rd, 2279, at 18:50:47 Standard Sol Time, the terraforming of Mars was officially declared complete.[linebreak]

For the first time in human history, a world other than Earth had been made fully habitable.[linebreak]

Thus, humanity turned elsewhere.[sleep 1000][linebreak]
[sleep 700][function "end"]