{{# written 6 aug, 2026 #}}
typewriter: {
    charDelay: 46
    newlineDelay: 600
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 400
        ".": 600
        ":": 350
    }
    wordWrap: 110
}

[mixin "menu-prefix"]
[tab 1]>[tab 1 fill]
[mixin end]

[mixin "instant2"]
    [swap]
    [instant][@use "menu-prefix"]\[<String>\][tab 1 fill][instant off][newline]
    [instant][@use "menu-prefix"]\[<String>\][tab 1 fill][instant off]
    [swap]
[mixin end]

[mixin "instant5"]
    [swap]
    [instant][@use "menu-prefix"]\[<String>\][tab 1 fill][instant off][newline]
    [instant][@use "menu-prefix"]\[<String>\][tab 1 fill][instant off][newline]
    [instant][@use "menu-prefix"]\[<String>\][tab 1 fill][instant off][newline]
    [instant][@use "menu-prefix"]\[<String>\][tab 1 fill][instant off][newline]
    [instant][@use "menu-prefix"]\[<String>\][tab 1 fill][instant off]
    [swap]
[mixin end]

{{# He felt a finger jab the back of his head,[sleep 200] twice.[sleep 200] The second time stronger.[sleep 300][newline]
“Hey, wake up.”[sleep 1380][newline]
[speed 48]After a moment of no reaction, he threw himself upright in [sleep 80]short\-lived, sleep\-deprived panic.[sleep 150][newline]
[custom "," 120][speed 42]
“Right, right,[sleep 400] sorry, sorry.”
[custom "," 400][sleep 400][speed 46][newline]
He rubbed his head, the sting already fading.[newline]
“Those reports won’t fill out themselves.”[sleep 150][newline]
“Yeah, yeah, I know.”[newline] #}}
“You better, Mercury Boy.”[sleep 700][linebreak]
[custom "," 600][custom "." 750][speed 48]
As she turned [sleep 50]and walked away, [speed 46]her outerwear rubbed against the tightly\-packed chairs that lined the narrow office. Her footsteps gradually became softer until they were swallowed by the hum of background noise.[linebreak]

He rubbed his eyes and stared blankly at his screen, slowly remembering what task he was attempting to complete before he fell asleep. His gaze wandered for a moment before settling on the obvious rows and rows of reports that required manual attention. He clicked the first one at the top.[linebreak]

[custom "," 200]

[speed 20]
[repeat "─" 110 instant][newline]
CARGO INCIDENT REPORT[linebreak]
CASE ID : 76674539[newline]
[tab 1]STATUS : PMR[newline]
[repeat "─" 110 instant][newline]
[tab 5]VESSEL NAME : Summer Solstice[newline]
VESSEL REGISTRAR : ERSK1[newline]
[tab 6]VESSEL RID : 4011[newline]
[tab 4]REGESTRATION : VALID[linebreak]

ROUTE[newline]
[tab 6]DEPARTURE : Ome Spaceport, Japan, ER[newline]
[tab 4]DESTINATION : Conamara Station, EP, ZU[linebreak]

TIME SUBMITTED: [customremove ":"]2214\-08\-15 4:[linebreak instant]

[custom "," 300]
[custom "." 650]

[speed 60]And right about now was when his brain went on autopilot. He used to take his job with utmost seriousness. His decisions decided if someone got fined, got warned, got visited by someone, or something else. He used to watch himself, making sure he scrutinized every single character\- every single pixel. But now, after a year or so–or two, or half–he didn’t care. If he was sad, or mad, or angry, it reflected in his reports. His mood swings and his temper tantrums caused someone something, probably. He barely saw a report. It was just pixels.[linebreak]

He only felt each key slam under his fingers, pushing back up as if to help it along to the next. He felt the hollow ring they produced through the memory of his fingertips, time and space blending with pixels and plastic. That’s all it was, pixels, pixels, pixels, and pixels. Click next. Type words. Dropdown. Close. Next. Type words. Dropdown. Request Clarification. Next. Type words. Dropdown. Escalate. Next. Type words. Dropdown. Close. It was all just pixels. All just pixels.[linebreak]

The reports blended together. The first into the second, the second into the third, and so on, and so on. His hands moved even before his eyes did; opening windows, ticking boxes, discarding useless testimonies. Another cargo incident. Another minor collision. Another chang[linebreak instant]

Unknown[linebreak]

He read and reread the word multiple times. That word wasn’t supposed to be there. He backtracked, looking for what exactly was unknown.[linebreak]

DESTINATION: Unknown Station, AR[newline]
Approximate Location: 18°S 140°E[linebreak]

Unknown station? Every station in the solar system was registered. It had to be. You couldn’t dock with it, supply it, insure it, even acknowledge it without it being registered. The automated system should’ve rejected rejected this report outright, he should’ve never even seen it. He looked at what came after.[linebreak]

AR. Mars. The unknown station was on Mars. He looked at the line after.[linebreak]

Approximate Location: 18°S 140°E[linebreak]

They even knew where it was. Why was it listed as unknown then?[linebreak]

He opened the database of all registered stations. As an ITA employee, he had access to these kinds of luxuries. Switching to coordinate search, he entered the latitude and longitude exactly as they appeared on the report. He pressed enter, and waited a few seconds for the database to filter the results.[linebreak]

No results found.[linebreak]

Fine. It was a filing error then.[linebreak]

He clicked back to the report itself, and hit the actions button. A small menu unfolded near his cursor. He read the options he was presented with.[linebreak]

[@use "instant2" "Close" "Archive"][linebreak]

He frowned, and read them again.[linebreak]

[@use "instant2" "Close" "Archive"][linebreak]

Where was report filing error?[linebreak]

He closed the program, just to reopen it a moment later. He selected the report again and opened the actions menu.[linebreak]

[@use "instant2" "Close" "Archive"][linebreak]

It was still there. He tried a different report.[linebreak]

[@use "instant5" "Close" "Request Clarification" "Report Filing Error" "Escalate" "Archive"][linebreak]

The option still existed. They hadn’t done away with it, at least. He clicked back to the original report.[linebreak]

[@use "instant2" "Close" "Archive"][linebreak]

“um... Amy?” He called out, turning his head slightly, but keeping his eyes locked to the screen.[newline]
“What?”[newline]
Her voice originated from somewhere down the row, softened by distance and carpet.[newline]
“Could’ya come here for a sec, I got a problem.”[newline]
She hesitated slightly. “Be right there.”[newline]
He could hear her footsteps get louder and louder, before stopping right behind him. Her jacket once again rubbed against the office chairs.[newline]
“What?”[newline]
He pointed at the screen.[newline]
“The report filing error button is missing.”[newline]
She took control of his mouse somewhat forcefully. She closed the dropdown, just to click on the actions menu again. The same dropdown reappeared. She was silent for a few moments.[newline]
“Did you reopen the report?”[newline]
“Yes.”[newline]
“Restart the program?”[newline]
“Yeah.”[newline]
“Did you check another report?”[newline]
“Yeah. The button’s there.”[newline]
She went quiet for a second.[newline]
“So?”[newline]
“So... it’s missing.”[newline]
She sighed.[newline]
“What do you want me to do about it?[newline]
“What?”[newline]
“What do you want me to do about it, Mercury Boy?” She accented every consonant.[newline]
“I don’t know, isn’t this like, your thing? Everyone asks you about computer problems.”[newline]
“Not this one. Call IT.”[newline]
Before he could reply, she left, weaving through the chairs back to her desk at the far side of the office.[linebreak]

He added the report to his watch list, closed it, and opened the next one.[linebreak]


[sleep 700][function "end"]