{{# written 27 sept, 2026 #}}
typewriter: {
    charDelay: 50
    newlineDelay: 500
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 350
        ".": 600
    }
}
[function "image" "src/images/s23_slash.png" 248 350 1][linebreak]
[function "image" "src/images/s23_accel.png" 248 350 1][linebreak]
[function "image" "src/images/s23_slash_accel.png" 248 350 1][newline]
[sleep 1700][linebreak]
[function "end"]
