{{# written 11 sept, 2026 #}}
typewriter: {
    charDelay: 50
    newlineDelay: 500
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 350
        ".": 600
    }
}
[speed 200][custom "\n" 3000]
[speed 210]Our great he[speed 290]li[speed 201][sleep 120]x h[speed 190]as [sleep 200]come to y[speed 195]ou.[newline]
Rej[sleep 500]oice.[newline]
Be happ[speed 50][repeat 10][removelast 1]p[repeat end][speed 200]y.[newline][sleep 899]
We [sleep 39]have com[jitter "e" 7].[newline]
Be ha[jitter "p" 3]py.[newline]
We saw you.[newline]
[jitter "Our " 3 shared][jitter "home " 3 shared][sleep 120][jitter "is " 3 shared][jitter "gone." 3 shared][newline]
We come[sleep 200] to you.[newline]
We prepared.[newline]
[jitter "Not e" 5][sleep 130][jitter "nough." 5][newline]
[jitter "Only us." 10][newline]
[jitter "We offer yo" 15][sleep 333][jitter "u." 15][newline]
[jitter "Give us home." 20][newline]
[jitter "And we will share." 35][newline]
[jitter "To you." 45][newline]
[jitter "What we k" 55][sleep 544][jitter "now." 55][newline]
[function "jitterlerp" "êh÷nā ďoċ üoĈ Ĉeùiûvÿný ċsÄ" 250 300][newline]
[function "jitterlerp" "OůrĚpśnũpŮiŝoŨ." 50 200][newline]
[function "jitterlerp" "ɨeɆhʇpʖyɔ" 250 500][newline]




[linebreak instant][newline instant]
[sleep 1700][function "end"]
