{{# written 23 sept, 2026 #}}
typewriter: {
    charDelay: 60
    newlineDelay: 1380
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 600
        ";": 600
        ".": 800
    }
    wordWrap: 110
}

[mixin "red"]
[gradient <String> "to top right, #bb2e15, #f83232"]
[mixin end]

[mixin "green"]
[gradient <String> "to top right, #24b500, #2df82d"]
[mixin end]

[mixin "blue"]
[gradient <String> "to top right, #7c7cff, #9f9fff"]
[mixin end]

The [@use "red" "red"] sands of Mars were quite profound, really.[newline]
I remember touching down like it was yesterday.[newline]
I remember seeing the carved cliffs in the distance,[newline]
formed millennia ago.[linebreak]

They told us it was an easy job. A quick job.[newline]
They lied.[newline]
I used to be mad at them; furious.[newline]
But now, not so much.[newline]
Because I got used to it.[newline][sleep 700]
All the [@use "red" "red"].[newline]
All the machinery.[newline]
All the dust.[newline]
All the death.[linebreak]

It was awful.[newline]
You’d never go a day without someone dying. In every sector.[newline]
Japanese, Russians, Armenians, Us. Even the Americans.[newline]
Someone, somewhere, was always dying.[linebreak]

I will...[sleep 600] miss the [@use "red" "red"] sands, to be honest.[newline]
The [@use "blue" "blue"] sunsets.[newline]
It was all so /beautiful/.[linebreak]

But you,[newline]
you will see endless [@use "green" "green"],[newline]
in every direction,[newline]
with Olympus towering above.[newline]
And you’ll be able to sit at its base,[newline]
wearing nothing but a shirt and shorts.[newline]
Well... pants, probably. I heard that even after the terraforming, it will still be quite cold.[newline]
But not as cold as it is now.[sleep 970][linebreak]


How I envy you,[newline]
being born on a new planet.[newline]
One untouched by the plight of human hand.[newline]
You must take care of this planet.[newline]
Do not let us repeat the same mistakes we once did.[newline]
With Earth.[sleep 320] Our ancestral home.[newline]
Do not let Mars become it.[sleep 970][linebreak]

My son,[newline]
do not become complacent.[newline]
If the [@use "red" "red"] sands of terror begin to encroach upon this planet once more,[newline]
you must sow the soil.[newline]
You must till until the [@use "red" "rusty"] sands become [@use "green" "lush"].[newline]
You must not be blinded by the beautiful [@use "blue" "blue"] sunset.[linebreak]

You must walk forward,[newline]
step by step,[newline]
into the [@use "red" "red"] sunset of tomorrow.[sleep 1000][linebreak]

To my son,[newline]
[glitch 4].[sleep 1200][linebreak]
[speed 120]0047\/[sleep 900]06\/[sleep 900]21

[sleep 1700][linebreak]
[function "end"]
